
export const ADD_DISTRICT_REQUEST = 'ADD_DISTRICT_REQUEST';
export const ADD_DISTRICT_SUCCESS = 'ADD_DISTRICT_SUCCESS';
export const ADD_DISTRICT_FAIL = 'ADD_DISTRICT_FAIL';

export const ADD_TEHSIL_REQUEST = 'ADD_TEHSIL_REQUEST';
export const ADD_TEHSIL_SUCCESS = 'ADD_TEHSIL_SUCCESS';
export const ADD_TEHSIL_FAIL = 'ADD_TEHSIL_FAIL';

export const ADD_UC_REQUEST = 'ADD_UC_REQUEST';
export const ADD_UC_SUCCESS = 'ADD_UC_SUCCESS';
export const ADD_UC_FAIL = 'ADD_UC_FAIL';

export const ADD_VILLAGE_REQUEST = 'ADD_VILLAGE_REQUEST';
export const ADD_VILLAGE_SUCCESS = 'ADD_VILLAGE_SUCCESS';
export const ADD_VILLAGE_FAIL = 'ADD_VILLAGE_FAIL';

export const LIST_DISTRICT_REQUEST = 'LIST_DISTRICT_REQUEST';
export const LIST_DISTRICT_SUCCESS = 'LIST_DISTRICT_SUCCESS';
export const LIST_DISTRICT_FAIL = 'LIST_DISTRICT_FAIL';

export const LIST_TEHSIL_REQUEST = 'LIST_TEHSIL_REQUEST';
export const LIST_TEHSIL_SUCCESS = 'LIST_TEHSIL_SUCCESS';
export const LIST_TEHSIL_FAIL = 'LIST_TEHSIL_FAIL';

export const LIST_UC_REQUEST = 'LIST_UC_REQUEST';
export const LIST_UC_SUCCESS = 'LIST_UC_SUCCESS';
export const LIST_UC_FAIL = 'LIST_UC_FAIL';

export const LIST_VILLAGE_REQUEST = 'LIST_VILLAGE_REQUEST';
export const LIST_VILLAGE_SUCCESS = 'LIST_VILLAGE_SUCCESS';
export const LIST_VILLAGE_FAIL = 'LIST_VILLAGE_FAIL';

export const DElETE_DISTRICT_REQUEST = 'DElETE_DISTRICT_REQUEST';
export const DElETE_DISTRICT_SUCCESS = 'DElETE_DISTRICT_SUCCESS';
export const DElETE_DISTRICT_FAIL = 'DElETE_DISTRICT_FAIL';

export const DElETE_TEHSIL_REQUEST = 'DElETE_TEHSIL_REQUEST';
export const DElETE_TEHSIL_SUCCESS = 'DElETE_TEHSIL_SUCCESS';
export const DElETE_TEHSIL_FAIL = 'DElETE_TEHSIL_FAIL';

export const DElETE_UC_REQUEST = 'DElETE_UC_REQUEST';
export const DElETE_UC_SUCCESS = 'DElETE_UC_SUCCESS';
export const DElETE_UC_FAIL = 'DElETE_UC_FAIL';

export const DElETE_VILLAGE_REQUEST = 'DElETE_VILLAGE_REQUEST';
export const DElETE_VILLAGE_SUCCESS = 'DElETE_VILLAGE_SUCCESS';
export const DElETE_VILLAGE_FAIL = 'DElETE_VILLAGE_FAIL';

export const UPDATE_DISTRICT_REQUEST = 'UPDATE_DISTRICT_REQUEST';
export const UPDATE_DISTRICT_SUCCESS = 'UPDATE_DISTRICT_SUCCESS';
export const UPDATE_DISTRICT_FAIL = 'UPDATE_DISTRICT_FAIL';

export const UPDATE_TEHSIL_REQUEST = 'UPDATE_TEHSIL_REQUEST';
export const UPDATE_TEHSIL_SUCCESS = 'UPDATE_TEHSIL_SUCCESS';
export const UPDATE_TEHSIL_FAIL = 'UPDATE_TEHSIL_FAIL';

export const UPDATE_UC_REQUEST = 'UPDATE_UC_REQUEST';
export const UPDATE_UC_SUCCESS = 'UPDATE_UC_SUCCESS';
export const UPDATE_UC_FAIL = 'UPDATE_UC_FAIL';

export const UPDATE_VILLAGE_REQUEST = 'UPDATE_VILLAGE_REQUEST';
export const UPDATE_VILLAGE_SUCCESS = 'UPDATE_VILLAGE_SUCCESS';
export const UPDATE_VILLAGE_FAIL = 'UPDATE_VILLAGE_FAIL';