export const USERROSTER_LIST_REQUEST = 'USERROSTER_LIST_REQUEST';
export const USERROSTER_LIST_SUCCESS = 'USERROSTER_LIST_SUCCESS';
export const USERROSTER_LIST_FAIL = 'USERROSTER_LIST_FAIL';

export const USERROSTER_LIST_BYID_REQUEST = 'USERROSTER_LIST_BYID_REQUEST';
export const USERROSTER_LIST_BYID_SUCCESS = 'USERROSTER_LIST_BYID_SUCCESS';
export const USERROSTER_LIST_BYID_FAIL = 'USERROSTER_LIST_BYID_FAIL';

export const USERDETAILS_LIST_REQUEST = 'USERDETAILS_LIST_REQUEST';
export const USERDETAILS_LIST_SUCCESS = 'USERDETAILS_LIST_SUCCESS';
export const USERDETAILS_LIST_FAIL = 'USERDETAILS_LIST_FAIL';

export const CHECKLIST_LIST_REQUEST = 'CHECKLIST_LIST_REQUEST';
export const CHECKLIST_LIST_SUCCESS = 'CHECKLIST_LIST_SUCCESS';
export const CHECKLIST_LIST_FAIL = 'CHECKLIST_LIST_FAIL';

export const LOCATIONUPDATES_LIST_REQUEST = 'LOCATIONUPDATES_LIST_REQUEST';
export const LOCATIONUPDATES_LIST_SUCCESS = 'LOCATIONUPDATES_LIST_SUCCESS';
export const LOCATIONUPDATES_LIST_FAIL = 'LOCATIONUPDATES_LIST_FAIL';

export const ADD_CHECKLIST_REQUEST = 'ADD_CHECKLIST_REQUEST';
export const ADD_CHECKLIST_SUCCESS = 'ADD_CHECKLIST_SUCCESS';
export const ADD_CHECKLIST_FAIL = 'ADD_CHECKLIST_FAIL';

export const CHECKLISTCENTER_DELETE_REQUEST = 'CHECKLISTCENTER_DELETE_REQUEST';
export const CHECKLISTCENTER_DELETE_SUCCESS = 'CHECKLISTCENTER_DELETE_SUCCESS';
export const CHECKLISTCENTER_DELETE_FAIL = 'CHECKLISTCENTER_DELETE_FAIL';

export const CHECKLISTCENTER_UPDATE_REQUEST = 'CHECKLISTCENTER_UPDATE_REQUEST';
export const CHECKLISTCENTER_UPDATE_SUCCESS = 'CHECKLISTCENTER_UPDATE_SUCCESS';
export const CHECKLISTCENTER_UPDATE_FAIL = 'CHECKLISTCENTER_UPDATE_FAIL';

